// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_d/test/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter/material.dart' as _i9;
import 'package:mobile_d/data/datasources/local/database_helper.dart' as _i4;
import 'package:mobile_d/data/datasources/local/preferences_helper.dart' as _i2;
import 'package:mobile_d/data/datasources/remote/api_service.dart' as _i3;
import 'package:mobile_d/data/datasources/remote/updates_service.dart' as _i8;
import 'package:mobile_d/data/models/auth_model.dart' as _i7;
import 'package:mobile_d/data/repositories/auth_repository.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePreferencesHelper_0 extends _i1.SmartFake
    implements _i2.PreferencesHelper {
  _FakePreferencesHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiService_1 extends _i1.SmartFake implements _i3.ApiService {
  _FakeApiService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseHelper_2 extends _i1.SmartFake
    implements _i4.DatabaseHelper {
  _FakeDatabaseHelper_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PreferencesHelper get preferences =>
      (super.noSuchMethod(
            Invocation.getter(#preferences),
            returnValue: _FakePreferencesHelper_0(
              this,
              Invocation.getter(#preferences),
            ),
          )
          as _i2.PreferencesHelper);

  @override
  _i3.ApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeApiService_1(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i3.ApiService);

  @override
  _i6.Future<_i7.AuthModel?> login(_i7.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i6.Future<_i7.AuthModel?>.value(),
          )
          as _i6.Future<_i7.AuthModel?>);

  @override
  _i6.Future<_i7.AuthModel?> register(_i7.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i6.Future<_i7.AuthModel?>.value(),
          )
          as _i6.Future<_i7.AuthModel?>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i7.AuthModel?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i6.Future<_i7.AuthModel?>.value(),
          )
          as _i6.Future<_i7.AuthModel?>);
}

/// A class which mocks [UpdatesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatesService extends _i1.Mock implements _i8.UpdatesService {
  MockUpdatesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeApiService_1(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i3.ApiService);

  @override
  _i4.DatabaseHelper get databaseHelper =>
      (super.noSuchMethod(
            Invocation.getter(#databaseHelper),
            returnValue: _FakeDatabaseHelper_2(
              this,
              Invocation.getter(#databaseHelper),
            ),
          )
          as _i4.DatabaseHelper);

  @override
  _i2.PreferencesHelper get preferencesHelper =>
      (super.noSuchMethod(
            Invocation.getter(#preferencesHelper),
            returnValue: _FakePreferencesHelper_0(
              this,
              Invocation.getter(#preferencesHelper),
            ),
          )
          as _i2.PreferencesHelper);

  @override
  _i6.Future<void> getUpdates(_i9.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getUpdates, [context]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
