// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_d/test/transaction_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dio/dio.dart' as _i3;
import 'package:mobile_d/data/datasources/local/database_helper.dart' as _i6;
import 'package:mobile_d/data/datasources/remote/api_service.dart' as _i9;
import 'package:mobile_d/data/models/auth_model.dart' as _i4;
import 'package:mobile_d/data/models/category_model.dart' as _i8;
import 'package:mobile_d/data/models/transaction_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthModel_3 extends _i1.SmartFake implements _i4.AuthModel {
  _FakeAuthModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionModel_4 extends _i1.SmartFake
    implements _i5.TransactionModel {
  _FakeTransactionModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i6.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i7.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i7.Future<_i2.Database>);

  @override
  _i7.Future<_i2.Database> initDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#initDatabase, []),
            returnValue: _i7.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.method(#initDatabase, [])),
            ),
          )
          as _i7.Future<_i2.Database>);

  @override
  _i7.Future<int> insertTransaction(_i5.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#insertTransaction, [transaction]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i5.TransactionModel>> getTransactions(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, [userId]),
            returnValue: _i7.Future<List<_i5.TransactionModel>>.value(
              <_i5.TransactionModel>[],
            ),
          )
          as _i7.Future<List<_i5.TransactionModel>>);

  @override
  _i7.Future<List<_i5.TransactionModel>> getTransactionsByDateRange(
    DateTime? start,
    DateTime? end,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByDateRange, [
              start,
              end,
              userId,
            ]),
            returnValue: _i7.Future<List<_i5.TransactionModel>>.value(
              <_i5.TransactionModel>[],
            ),
          )
          as _i7.Future<List<_i5.TransactionModel>>);

  @override
  _i7.Future<int> updateTransaction(_i5.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> updateAllTransactions(
    List<_i5.TransactionModel>? transactions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAllTransactions, [transactions]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i8.CategoryModel>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i7.Future<List<_i8.CategoryModel>>.value(
              <_i8.CategoryModel>[],
            ),
          )
          as _i7.Future<List<_i8.CategoryModel>>);

  @override
  _i7.Future<void> updateAllCategories(List<_i8.CategoryModel>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#updateAllCategories, [categories]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i9.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_1(this, Invocation.getter(#dio)),
          )
          as _i3.Dio);

  @override
  _i7.Future<_i3.Response<dynamic>> requestPost(
    String? path,
    Map<dynamic, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestPost, [path, data]),
            returnValue: _i7.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(#requestPost, [path, data]),
              ),
            ),
          )
          as _i7.Future<_i3.Response<dynamic>>);

  @override
  _i7.Future<_i4.AuthModel> login(_i4.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i7.Future<_i4.AuthModel>.value(
              _FakeAuthModel_3(this, Invocation.method(#login, [request])),
            ),
          )
          as _i7.Future<_i4.AuthModel>);

  @override
  _i7.Future<_i4.AuthModel> register(_i4.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i7.Future<_i4.AuthModel>.value(
              _FakeAuthModel_3(this, Invocation.method(#register, [request])),
            ),
          )
          as _i7.Future<_i4.AuthModel>);

  @override
  _i7.Future<List<_i5.TransactionModel>> fetchTransactions(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTransactions, [userId]),
            returnValue: _i7.Future<List<_i5.TransactionModel>>.value(
              <_i5.TransactionModel>[],
            ),
          )
          as _i7.Future<List<_i5.TransactionModel>>);

  @override
  _i7.Future<_i5.TransactionModel> createTransaction(
    _i5.TransactionModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [transaction]),
            returnValue: _i7.Future<_i5.TransactionModel>.value(
              _FakeTransactionModel_4(
                this,
                Invocation.method(#createTransaction, [transaction]),
              ),
            ),
          )
          as _i7.Future<_i5.TransactionModel>);

  @override
  _i7.Future<void> updateTransaction(_i5.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteTransaction(int? id, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id, userId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.CategoryModel>> fetchCategories() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategories, []),
            returnValue: _i7.Future<List<_i8.CategoryModel>>.value(
              <_i8.CategoryModel>[],
            ),
          )
          as _i7.Future<List<_i8.CategoryModel>>);

  @override
  _i7.Future<void> updateBudgetLimit(int? userId, double? budgetLimit) =>
      (super.noSuchMethod(
            Invocation.method(#updateBudgetLimit, [userId, budgetLimit]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
